name: fire_base
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  firebase_core: ^2.20.0
  flutter: 
    sdk: flutter
  firebase_auth: 4.12.0
  intl: ^0.18.1
  cloud_firestore: ^4.12.2
  firebase_storage: ^11.4.1
  nb_utils: ^6.0.6
  convex_bottom_bar: ^3.2.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/login.png
    - assets/images/profile.png
    - assets/images/avatar.png
    - assets/images/home.png
    - assets/images/form.png
  uses-material-design: true

